apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-prometheus-stack-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"  # Update with the appropriate StorageClass name
  awsElasticBlockStore:
    volumeID: vol-03fecdcfa4914dbef  # Replace with your EBS volume ID
    fsType: ext4
